version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: 'host'
    ports:
    - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    network_mode: 'host'
    ports:
    - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_HOST_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'